### ISSUE TITLE
Markdown Syntax-Highlighter

### ISSUE THREAD

**Issue by acambule** [mriscoc/mdEditor#1]
Hello,

first, im sorry to write here as issue, i didn't know how to contact you otherwise.

I'm looking for an markdown syntax-highlighter for synedit (in delphi).
I've seen you are using synedit for your Editor and markdown is highlighted in your screenshots.

How did you achieve it? Have you written your own one? 
Would you mind to share it?

Thanks and regards
Antonio

**Comment by mriscoc** [comment]
Hi Antonio,
No, I do not have a markdown syntax-highlighter, I had to use the html highlighter for now.
